/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import tbs.hotel.*;
import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;


public final class RESERVATION extends javax.swing.JFrame {
     private static Connection koneksi; //untuk koneksi
    private DefaultTableModel model; //untuk model tabel pada form
   ResultSet Rs;
   Statement stm;
   Connection con;
    /**
     * Creates new form RESERVATION
     */
    public RESERVATION() {
   initComponents();
        ClearForm();
        tampildataivan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_tempat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbx_tempat = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        txt_ktp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BTN_DELETE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chk_in = new com.toedter.calendar.JDateChooser();
        chk_out = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_hp = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1281, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check In");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check Out");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tipe");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        txt_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_namaFocusLost(evt);
            }
        });
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 220, -1));

        txt_tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tempatActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("1. Standart");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("2. Superior");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("3. Deluxe");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("4. Executive");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        cbx_tempat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        cbx_tempat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_tempatItemStateChanged(evt);
            }
        });
        cbx_tempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tempatActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("HARGA");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 220, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NO.KTP", "Check In", "Check Out", "Tipe", "Harga", "ID ADMIN"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 610, 350));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 80, 30));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, 80, 30));
        getContentPane().add(txt_ktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 220, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No.KTP");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/Logo Hotel Sulfana.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -10, 90, 90));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 90, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Show all ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 90, 30));

        BTN_DELETE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_DELETE.setText("delete");
        BTN_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/LOG.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 30, 30));
        getContentPane().add(chk_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 220, -1));
        getContentPane().add(chk_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 220, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDING", "CONFIRMED", "CANCELLED" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No hp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        getContentPane().add(txt_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 220, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/WhatsApp Image 2025-01-06 at 22.01.17_527336c8.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void ClearForm(){
        txt_id.setText("");
        txt_nama .setText("");
        txt_ktp.setText("");
        txt_hp.setText("");
        chk_in.getDate();
        chk_out.getDate();
        txt_tempat.setText(""); 
        txt_harga.setText(""); 
        status.getSelectedItem();
    }
    
  
    public void tampildataivan() {
    model = new DefaultTableModel();
    this.jTable1.setModel(model);
    model.addColumn("id_transaksi");
    model.addColumn("nama");
    model.addColumn("no_ktp");
    model.addColumn("no_hp");
    model.addColumn("Tgl_masuk");
    model.addColumn("Tgl_keluar");
    model.addColumn("tempat");
    model.addColumn("harga");
    model.addColumn("status");

    String sql = "SELECT * FROM reservation";

    try (Connection conn = Db.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery()) {

        while (rs.next()) {
            // Ambil data sesuai kolom pada database
            String idreservasi = rs.getString("id_transaksi");
            String nama = rs.getString("nama");
            String noktp = rs.getString("no_ktp");
            String nohp = rs.getString("no_hp");
            String tglMasuk = rs.getString("check_in");
            String tglKeluar = rs.getString("check_out");
            String tempat = rs.getString("tipe");
            String harga = rs.getString("harga");
            String status = rs.getString("status");

            // Masukkan data ke dalam tabel
            model.addRow(new Object[] { idreservasi, nama, noktp, nohp, tglMasuk, tglKeluar, tempat, harga, status });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "TERJADI KESALAHAN! " + e.getMessage());
    }
}

    
private void klikTabel() {
    // Mendapatkan baris yang dipilih di jTable1
    int i = this.jTable1.getSelectedRow();
    if (i == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih baris dalam tabel terlebih dahulu.");
        return;
    }

    // Mengambil data dari model tabel berdasarkan indeks baris
    String id = (String) model.getValueAt(i, 0);
    this.txt_nama.setText(id);

    String nama = (String) model.getValueAt(i, 1);
    this.txt_ktp.setText(nama);

    String tglMasuk = (String) model.getValueAt(i, 2);
    try {
        // Konversi String tanggal menjadi java.util.Date
        SimpleDateFormat dateFormat = new SimpleDateFormat("mm-dd-yy"); // Format sesuai data di tabel
        java.util.Date dateIn = dateFormat.parse(tglMasuk);
        this.chk_in.setDate(dateIn); // Atur tanggal ke JDateChooser
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal check-in tidak valid: " + e.getMessage());
    }

    String tglKeluar = (String) model.getValueAt(i, 3);
    try {
        // Konversi String tanggal menjadi java.util.Date
        SimpleDateFormat dateFormat = new SimpleDateFormat("mm-dd-yy"); // Format sesuai data di tabel
        java.util.Date dateOut = dateFormat.parse(tglKeluar);
        this.chk_out.setDate(dateOut); // Atur tanggal ke JDateChooser
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal check-out tidak valid: " + e.getMessage());
    }

    String tempat = (String) model.getValueAt(i, 4);
    this.txt_tempat.setText(tempat);

    String harga = (String) model.getValueAt(i, 5);
    this.txt_harga.setText(harga);

}

  
   public void hargaHOTEL(){ //create method gajipokok
        int pilihan=cbx_tempat.getSelectedIndex();
        switch(pilihan){
            case 0:
                txt_harga.setText("");
            break;
            case 1:
                txt_harga.setText("400.000");
            break;
            case 2:
                txt_harga.setText("1.500.000");
            break;
            case 3:
                txt_harga.setText("2.500.000");
            break;
             case 4:
                txt_harga.setText("4.000.000");
            break;
        }
    }
   
     public void tempat(){ 
        int pilihan= cbx_tempat.getSelectedIndex();
        switch(pilihan){
            case 0:
                txt_tempat.setText("");
            break;
            case 1:
                txt_tempat.setText("Standart");
            break;
            case 2:
                txt_tempat.setText("Superior");
            break;
            case 3:
                txt_tempat.setText("Deluxe");
            break;
             case 4:
                txt_tempat.setText("Executive");
            break;
        }
    }
    private void cbx_tempatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_tempatItemStateChanged

        
         tempat();
        txt_tempat.setEnabled(false);
         hargaHOTEL();
        txt_harga.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tempatItemStateChanged

    private void BTN_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DELETEActionPerformed
    int ok = JOptionPane.showConfirmDialog(
        null, 
        "Apakah yakin untuk Menghapus Data ini?", 
        "Confirmation", 
        JOptionPane.YES_NO_OPTION
    );

    if (ok == JOptionPane.YES_OPTION) {
        // Ambil ID_transaksi dari komponen GUI (misalnya, dari teks field atau tabel)
        String idTransaksi = txt_id.getText(); // Pastikan txt_nama berisi ID_transaksi
        if (idTransaksi == null || idTransaksi.isEmpty()) {
            JOptionPane.showMessageDialog(
                null, 
                "Pilih data dari tabel terlebih dahulu!"
            );
            return;
        }

        String sql = "DELETE FROM reservation WHERE id_transaksi = ?";
        try (Connection conn = Db.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // Mengatur nilai parameter untuk query DELETE
            pstmt.setString(1, idTransaksi);

            // Eksekusi query DELETE
            int rowsAffected = pstmt.executeUpdate();

            // Periksa apakah ada baris yang dihapus
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(
                    null, 
                    "Data berhasil dihapus!"
                );

                // Bersihkan form setelah penghapusan
                ClearForm();

                // Muat ulang data di tabel setelah penghapusan
                tampildataivan();
            } else {
                JOptionPane.showMessageDialog(
                    null, 
                    "Data gagal dihapus. Periksa ID_transaksi."
                );
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                null, 
                "Terjadi kesalahan: " + e.getMessage()
            );
        }
    }
    }//GEN-LAST:event_BTN_DELETEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    tampildataivan();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusLost
        // TODO add your handling code here:
//        con=konekDB();
//       try {
//        // Gunakan prepared statement untuk keamanan
//        String query = "SELECT * FROM RESERVATION WHERE id_transaksi = ?";
//        try (PreparedStatement stm = con.prepareStatement(query)) {
//            stm.setString(1, txt_nama.getText().trim()); // Input dari txt_nama
//            
//            // Eksekusi query
//            ResultSet rs = stm.executeQuery();
//            if (rs.next()) {
//                // Ambil data dari database dan atur ke komponen
//                txt_ktp.setText(rs.getString("id_user"));
//                
//                // Set tanggal ke JDateChooser
//                Date tglMasuk = rs.getDate("tgl_masuk");
//                Date tglKeluar = rs.getDate("tgl_keluar");
//                chk_in.setDate(tglMasuk);   // Set ke JDateChooser chk_in
//                chk_out.setDate(tglKeluar); // Set ke JDateChooser chk_out
//
//                txt_tempat.setText(rs.getString("tempat"));
//                txt_harga.setText(rs.getString("harga"));
//            } else {
//                JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
//            }
//        }
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
//        e.printStackTrace();
//    }
    }//GEN-LAST:event_txt_namaFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new LOGINATMIN().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       try {
    // Prompt input pengguna
    String cari = JOptionPane.showInputDialog("Masukkan Nama:");

    // Validasi input tidak kosong atau null
    if (cari == null || cari.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Input tidak boleh kosong.");
        return;
    }

    String sql = "SELECT * FROM reservation WHERE nama LIKE ?";

    try (Connection conn = Db.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, "%" + cari + "%");

        // Eksekusi query
        try (ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                txt_id.setText(rs.getString("id_transaksi")); // Sesuaikan nama kolom
                txt_nama.setText(rs.getString("nama")); // Sesuaikan nama kolom
                txt_ktp.setText(rs.getString("no_ktp")); // Sesuaikan nama kolom
                txt_hp.setText(rs.getString("no_hp")); // Sesuaikan nama kolom

                // Konversi string dari database ke java.util.Date
                try {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Format sesuai database
                    java.util.Date dateIn = dateFormat.parse(rs.getString("check_in")); // Sesuaikan nama kolom
                    java.util.Date dateOut = dateFormat.parse(rs.getString("check_out")); // Sesuaikan nama kolom

                    // Atur tanggal ke JDateChooser
                    chk_in.setDate(dateIn);
                    chk_out.setDate(dateOut);
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Kesalahan format tanggal: " + e.getMessage());
                }

                txt_tempat.setText(rs.getString("tipe")); // Sesuaikan nama kolom
                txt_harga.setText(rs.getString("harga")); // Sesuaikan nama kolom

            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan dalam database.");
            }
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    e.printStackTrace();
}


    


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

  try (Connection conn = Db.getConnection()) { // Pastikan Db.getConnection() sudah terhubung dengan database
    int ok = JOptionPane.showConfirmDialog(
        null,
        "Apakah yakin untuk Mengubah Data ini?",
        "Confirmation",
        JOptionPane.YES_NO_OPTION
    );

    if (ok == JOptionPane.YES_OPTION) {
        // Query untuk update data
        String sql = "UPDATE reservation SET " +
                     "id_transaksi=?, nama=?, no_ktp=?, check_in=?, check_out=?, " +
                     "tipe=?, harga=?, status=? " +
                     "WHERE id_transaksi=?";
                     
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            // Mengisi parameter untuk query
            ps.setString(1, txt_id.getText()); // ID Transaksi
            ps.setString(2, txt_nama.getText()); // Nama
            ps.setString(3, txt_ktp.getText()); // Nomor KTP
            ps.setString(4, new SimpleDateFormat("yyyy-MM-dd").format(chk_in.getDate())); // Tanggal check-in
            ps.setString(5, new SimpleDateFormat("yyyy-MM-dd").format(chk_out.getDate())); // Tanggal check-out
            ps.setString(6, txt_tempat.getText()); // Tipe kamar
            ps.setString(7, txt_harga.getText()); // Harga

            // Mengambil nilai dari ComboBox
            String statusValue = status.getSelectedItem().toString();
            ps.setString(8, statusValue);
            ps.setString(9, txt_id.getText()); // ID Transaksi untuk WHERE clause
            
            // Eksekusi update
            ps.executeUpdate();

            // Tampilkan data baru dan kosongkan form input
            tampildataivan();
            ClearForm();
            JOptionPane.showMessageDialog(null, "UPDATE DATA SUKSES");
        }
    }
} catch (SQLException | HeadlessException e) {
    JOptionPane.showMessageDialog(null, "UPDATE DATA GAGAL: " + e.getMessage());
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tempatActionPerformed

    private void cbx_tempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tempatActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        
    }//GEN-LAST:event_statusActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RESERVATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RESERVATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RESERVATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RESERVATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new LOGINATMIN().setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_DELETE;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cbx_tempat;
    private com.toedter.calendar.JDateChooser chk_in;
    private com.toedter.calendar.JDateChooser chk_out;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_hp;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_ktp;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tempat;
    // End of variables declaration//GEN-END:variables

    private void tampildata() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
}
